import 'package:flutter/material.dart';


Map<String, IconData> smartIcons = {
  'add': Icons.add,
  'menu': Icons.menu,
  'language': Icons.language,
  'email': Icons.email,
  'event': Icons.event,
  'category': Icons.category,
  'assessment': Icons.assessment,
  'create': Icons.create,
  'restaurant': Icons.restaurant,
  'translate': Icons.translate,
  'security': Icons.security,
  'plus_one': Icons.plus_one,
  'ac_unit': Icons.ac_unit,
  'access_alarm': Icons.access_alarm,
  'access_time': Icons.access_time,
  'accessibility': Icons.accessibility,
  'accessibility_new': Icons.accessibility_new,
  'accessible': Icons.accessible,
  'account_balance': Icons.account_balance,
  'account_box': Icons.account_box,
  'account_circle': Icons.account_circle,
  'account_tree': Icons.account_tree,
  'add_units': Icons.ad_units,
  'adb': Icons.adb,
  'add_alarm': Icons.add_alarm,
  'add_a_photo': Icons.add_a_photo,
  'add_box': Icons.add_box,
  'add_alert': Icons.add_alert,
  'add_business': Icons.add_business,
  'add_call': Icons.add_call,
  'add_chart': Icons.add_chart,
  'add_circle': Icons.add_circle,
  'add_comment': Icons.add_comment,
  'add_link': Icons.add_link,
  'add_location': Icons.add_location,
  'add_moderator': Icons.add_moderator,
  'add_road': Icons.add_road,
  'add_sharp': Icons.add_sharp,
  'add_to_photos': Icons.add_to_photos,
  'add_to_drive': Icons.add_to_drive,
  'add_to_queue': Icons.add_to_queue,
  'adjust': Icons.adjust,
  'agriculture': Icons.agriculture,
  'airline_seat_flat': Icons.airline_seat_flat,
  'airplanemode_off': Icons.airplanemode_off,
  'airplanemode_on': Icons.airplanemode_on,
  'airplay': Icons.airplay,
  'alarm': Icons.alarm,
  'album': Icons.album,
  'api': Icons.api,
  'amp_stories': Icons.amp_stories,
  'analytics': Icons.analytics,
  'alt_route': Icons.alt_route,
  'anchor': Icons.anchor,
  'apartment': Icons.apartment,
  'android': Icons.android,
  'announcement': Icons.announcement,
  'approval': Icons.approval,
  'apps': Icons.apps,
  'archive': Icons.archive,
  'attach_file': Icons.attach_file,
  'attachment': Icons.attachment,
  'attractions': Icons.attractions,
  'battery_alert': Icons.battery_alert,
  'backpack': Icons.backpack,
  'backspace': Icons.backspace,
  'backup': Icons.backup,
  'beach_access': Icons.beach_access,
  'battery_full': Icons.battery_full,
  'battery_unknown': Icons.battery_unknown,
  'biotech': Icons.biotech,
  'block': Icons.block,
  'bluetooth': Icons.bluetooth,
  'cached': Icons.cached,
  'cake': Icons.cake,
  'calculate': Icons.calculate,
  'call': Icons.call,
  'call_end': Icons.call_end,
  'call_missed': Icons.call_missed,
  'call_merge': Icons.call_merge,
  'clear_all': Icons.clear_all,
  'camera': Icons.camera,
  'card_travel': Icons.card_travel,
  'cases': Icons.cases,
  'cancel': Icons.cancel,
  'celebration': Icons.celebration,
  'cast': Icons.cast,
  'cloud_off': Icons.cloud_off,
  'close': Icons.close,
  'cloud': Icons.cloud,
  'closed_caption': Icons.closed_caption,
  'cloud_done': Icons.cloud_done,
  'chat': Icons.chat,
  'chat_bubble': Icons.chat_bubble,
  'colorize': Icons.colorize,
  'comment': Icons.comment,
  'check': Icons.check,
  'commute': Icons.commute,
  'compare': Icons.compare,
  'settings_display' : Icons.settings_display,
  'account_circle_rounded' : Icons.account_circle_rounded,
  'vpn_key' : Icons.vpn_key,
  'work' : Icons.work,
  'screen' : Icons.widgets,
  'assistant_navigation': Icons.assistant_navigation,
  'auto_awesome_mosaic' : Icons.auto_awesome_mosaic,
  'auto_awesome_motion' : Icons.auto_awesome_motion,
  'supervised_user_circle' : Icons.supervised_user_circle,
  'computer':Icons.computer,
  'auto_awesome' : Icons.auto_awesome,
  'ballot' : Icons.ballot,
  'branding_watermark' : Icons.branding_watermark,
  'ad_units' : Icons.ad_units,
  'all_inclusive' : Icons.all_inclusive,
  'assignment_late_rounded' : Icons.assignment_late_rounded,
  'dashboard' : Icons.dashboard
};